name: clipping
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.9
  - pandas
  - numpy
  - ipykernel
  - ipython
  - jupyter
  - sqlite
  - pip
  - pip:
      - boto3
      - botocore
      - omegaconf
#      - mysqlclient >= 2.1.0
      - psycopg[binary]
      - django
      -
      - djangorestframework
      - djangorestframework-simplejwt
      - django-cors-headers
      - python-decouple
      - openai