name: clipping
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.9
  - pandas
  - numpy
  - flask
  - ipykernel
  - ipython
  - jupyter
  - pip
  - pip:
      - boto3
      - botocore
      - omegaconf
      - flask_sqlalchemy