name: clipping
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.9
  - pandas
  - numpy
  - ipykernel
  - ipython
  - jupyter
  - sqlite
  - pip
  - pip:
      - boto3
      - botocore
      - omegaconf
      - django
      - mysqlclient
      - djangorestframework

