# Generated by Django 5.1.2 on 2024-10-29 14:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('bucket_name', models.CharField(max_length=100)),
                ('object_key', models.CharField(max_length=255)),
                ('file_type', models.SmallIntegerField(choices=[(1, 'Image'), (2, 'Video'), (3, 'Others')], default=3)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('tag', models.CharField(max_length=50, null=True)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(null=True)),
                ('user_id', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file',
            },
        ),
    ]
