# Generated by Django 5.1.2 on 2024-11-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
