# Generated by Django 5.1.2 on 2024-11-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_remove_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='bucket_name',
            field=models.CharField(default='clipping', max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
