# Generated by Django 5.1.2 on 2024-12-01 05:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_alter_file_bucket_name_alter_file_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='tag',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
