# Generated by Django 5.1.2 on 2024-12-03 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_alter_file_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='tag',
            new_name='tags',
        ),
    ]
