# Generated by Django 5.1.2 on 2025-01-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0007_fileinteraction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='fileinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment')], max_length=10),
        ),
    ]
