# Generated by Django 5.1.2 on 2025-02-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0010_alter_file_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
