# Generated by Django 5.1.2 on 2025-02-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
    ]
